// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB;
using LinqToDB.Data;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

#pragma warning disable 1573, 1591
#nullable enable

namespace FirebirdBooleanTester.Model
{
	public partial class TestDb : DataConnection
	{
		public TestDb()
		{
			InitDataContext();
		}

		public TestDb(string configuration)
			: base(configuration)
		{
			InitDataContext();
		}

		public TestDb(DataOptions<TestDb> options)
			: base(options.Options)
		{
			InitDataContext();
		}

		partial void InitDataContext();

		public ITable<Test> Tests => this.GetTable<Test>();
	}

	public static partial class ExtensionMethods
	{
		#region Table Extensions
		public static Test? Find(this ITable<Test> table, int id)
		{
			return table.FirstOrDefault(e => e.Id == id);
		}

		public static Task<Test?> FindAsync(this ITable<Test> table, int id, CancellationToken cancellationToken = default)
		{
			return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
		}
		#endregion
	}
}
